spring:
  datasource:
    url: dbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto=update: create